cluster.name: ${CLUSTER_NAME}
node.name: es03

# Network settings
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery settings
discovery.seed_hosts: ["es01", "es02"]
cluster.initial_master_nodes: ["es01"]

# Security settings
xpack.security.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.key: certs/es03/es03.key
xpack.security.http.ssl.certificate: certs/es03/es03.crt
xpack.security.http.ssl.certificate_authorities: certs/ca/ca.crt

xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.key: certs/es03/es03.key
xpack.security.transport.ssl.certificate: certs/es03/es03.crt
xpack.security.transport.ssl.certificate_authorities: certs/ca/ca.crt
xpack.security.transport.ssl.verification_mode: certificate

# License settings
xpack.license.self_generated.type: ${LICENSE}

# Machine learning and monitoring
xpack.ml.use_auto_machine_memory_percent: true
xpack.monitoring.collection.enabled: true

# Memory settings
bootstrap.memory_lock: false

# Node specialization - Data Worker
node.roles: ["data", "ingest", "remote_cluster_client"]
node.attr.node_type: worker

# Worker optimizations
indices.memory.index_buffer_size: 20%
thread_pool.write.queue_size: 1000

# Logging
logger.level: WARN
