use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "UPPERCASE")]
enum LogLevel {
    Critical,
    Warn,
    Info,
}

#[derive(Debug, Deserialize, Serialize)]
struct InnerMsg {
    device: String,
    msg: String,
    exceeded_values: Vec<bool>,
}

/// This struct matches the log json generated by the LogGen component
#[derive(Debug, Deserialize, Serialize)]
pub struct LogEntry {
    timestamp: DateTime<Utc>,
    level: LogLevel,
    temperature: f64,
    humidity: f64,
    msg: InnerMsg,
}
