[package]
name = "rust-logger"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
polars = { version = "0.49.1", features = ["lazy"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
